import KswissHeel from "../images/Group 18.png";
import Nike_Sneaker_11 from "../images/nike-sneakers-11.png";
import PumTrainSneakers from "../images/puma-train-sneakers.png";
import PumTrainSneakers_2 from "../images/pum-train-sneaker-2.png";
import FashionSneakers_II from "../images/Fashion-sneakers-II.png";
import EncapSneakers_n from "../images/Encap-sneakers-n.png";
import Kswiss_sneakers_II from "../images/K_swiss_sneakers_II.png";

const priceData4ScrollingPage = [
  {
    id: 110,
    Image: KswissHeel,
    productName: "K-swiss Heel",
    itemContainer: "items left",
    oldPrice: "$140,000",
    newPrice: "$200,000",
    discount: "-25%",
    itemLeft: 5
  },
  {
    id: 111,
    Image: Nike_Sneaker_11,
    productName: "Nike Sneakers 11",
    itemContainer: "items left",
    oldPrice: "$290,000",
    newPrice: "$200,000",
    discount: "-20%",
    itemLeft: 9
  },
  {
    id: 112,
    Image: PumTrainSneakers,
    productName: "Puma train Sneakers",
    itemContainer: "items left",
    oldPrice: "$200,000",
    newPrice: "$150,000",
    discount: "-10%",
    itemLeft: 13
  },
  {
    id: 113,
    Image: PumTrainSneakers_2,
    productName: "Puma train Sneakers 11",
    itemContainer: "items left",
    oldPrice: "$200,000",
    newPrice: "$150,000",
    discount: "-9%",
    itemLeft: 4
  },
  {
    id: 114,
    Image: FashionSneakers_II,
    productName: "Fashion Sneakers II",
    itemContainer: "items left",
    oldPrice: "$40,000",
    newPrice: "$50,000",
    discount: "-15%",
    itemLeft: 12
  },
  {
    id: 115,
    Image: EncapSneakers_n,
    productName: "Encap Sneakers N",
    itemContainer: "items left",
    oldPrice: "$40,000",
    newPrice: "$50,000",
     discount: "-30%",
     itemLeft: 7
  },
  {
    id: 116,
    Image: Kswiss_sneakers_II,
    productName: "K Swiss Sneakers II",
    itemContainer: "items left",
    oldPrice: "$40,000",
    newPrice: "$50,000",
     discount: "-13%",
     itemLeft: 8
  },
  {
    id: 117,
    Image: KswissHeel,
    productName: "K-swiss Heel",
    itemContainer: "items left",
    oldPrice: "$40,000",
    newPrice: "$50,000",
     discount: "-43%",
     itemLeft: 10
  },
  {
    id: 118,
    Image: KswissHeel,
    productName: "K-swiss puma",
    itemContainer: "items left",
    oldPrice: "$40,000",
    newPrice: "$40,000",
    discount: "-43%",
    itemLeft: 5
  },
];

const priceData4ProductDisplay = [
  {
    id: 1,
    Image: EncapSneakers_n,
    productName: "Encap Sneakers N",
    itemContainer: "items left",
    oldPrice: "$40,000",
    newPrice: "$70,000",
    category: "female Shoes",
    Brand: "K-swiss",
    discount: "-25%",
    Size: "6-20",
    itemLeft: 5
  },
  {
    id: 2,
    Image: Nike_Sneaker_11,
    productName: "Nike Sneakers 11",
    itemContainer: "items left",
    oldPrice: "$290,000",
    newPrice: "$200,000",
     category: "male Shoes",
     discount: "-15%",
       Brand: "Nike",
       Size: "20-30",
       itemLeft: 2
  },
  {
    id: 3,
    Image: PumTrainSneakers,
    productName: "Puma train Sneakers",
    itemContainer: " items left",
    oldPrice: "$200,000",
    newPrice: "$150,000",
     category: "male Shoes",
     discount: "-30%",
     Brand: "Puma",
     Size: "31-40",
     itemLeft: 10
  },
  {
    id: 4,
    Image: FashionSneakers_II,
    productName: "Fashion Sneakers II",
    itemContainer: " items left",
    oldPrice: "$200,000",
    newPrice: "$150,000",
     category: "male Shoes",
     discount: "-20%",
     Brand: "Puma",
     Size: "41-50",
     itemLeft: 8
  },
  {
    id: 5,
    Image: PumTrainSneakers,
    productName: "Puma train Sneakers",
    itemContainer: "5 items left",
    oldPrice: "$200,000",
    newPrice: "$150,000",
    category: "male Shoes",
    Brand: "Puma",
    Size: "6-20",
    discount: "-43%",
    itemLeft: 8
  },
  {
    id: 6,
    Image: Nike_Sneaker_11,
    productName: "Nike Sneakers 11",
    itemContainer: "items left",
    oldPrice: "$290,000",
    newPrice: "$200,000",
    category: "male Shoes",
    Brand: "Nike",
    Size: "20-30",
    discount: "-43%",
    itemLeft: 8
  },
  {
    id: 7,
    Image: Kswiss_sneakers_II,
    productName: "K Swiss Sneaker II",
    itemContainer: "items left",
    oldPrice: "$200,000",
    newPrice: "$150,000",
    category: "male Shoes",
    Brand: "Puma",
    Size: "31-40",
    discount: "-43%",
    itemLeft: 14
  },
  {
    id: 8,
    Image: PumTrainSneakers_2,
    productName: "Puma train Sneakers 11",
    itemContainer: "10 items left",
    oldPrice: "$200,000",
    newPrice: "$150,000",
    category: "male Shoes",
    Brand: "Puma",
    Size: "41-50",
    discount: "-13%",
    itemLeft: 8
  },
  {
    id: 9,
    Image: KswissHeel,
    productName: "K-swiss Heel",
    itemContainer: "10 items left",
    oldPrice: "$40,000",
    newPrice: "$50,000",
    category: "female Shoes",
    Brand: "K-swiss",
    Size: "6-20",
    discount: "-23%"
  },
  {
    id: 10,
    Image: KswissHeel,
    productName: "K-swiss Heel",
    itemContainer: "10 items left",
    oldPrice: "$40,000",
    newPrice: "$50,000",
    category: "female Shoes",
    discount: "-33%"
  },
  {
    id: 11,
    Image: KswissHeel,
    productName: "K-swiss Heel",
    itemContainer: "10 items left",
    oldPrice: "$40,000",
    newPrice: "$50,000",
    category: "female Shoes",
    discount: "-23%"
  },
  {
    id: 12,
    Image: KswissHeel,
    productName: "K-swiss Heel",
    itemContainer: "10 items left",
    oldPrice: "$40,000",
    newPrice: "$50,000",
    category: "female Shoes",
      discount: "-13%"
  },

  {
    id: 13,
    Image: KswissHeel,
    productName: "K-swiss Heel",
    itemContainer: "10 items left",
    oldPrice: "$40,000",
    newPrice: "$670,000",
    category: "female Shoes",
      discount: "-31%"
  },
  {
    id: 14,
    Image: Nike_Sneaker_11,
    productName: "Nike Sneakers 11",
    itemContainer: "5 items left",
    oldPrice: "$290,000",
    newPrice: "$230,000",
    category: "male Shoes",
      discount: "-23%"
  },
  {
    id: 15,
    Image: PumTrainSneakers,
    productName: "Puma train Sneakers",
    itemContainer: "5 items left",
    oldPrice: "$200,000",
    newPrice: "$850,000",
    category: "male Shoes",
      discount: "-30%"
  },
  {
    id: 16,
    Image: PumTrainSneakers,
    productName: "Puma train Sneakers",
    itemContainer: "5 items left",
    oldPrice: "$200,000",
    newPrice: "$450,000",
    category: "male Shoes",
      discount: "-20%"
  },
  {
    id: 17,
    Image: PumTrainSneakers,
    productName: "Puma train Sneakers",
    itemContainer: "5 items left",
    oldPrice: "$200,000",
    newPrice: "$650,000",
    category: "male Shoes",
      discount: "-21%"
  },
  {
    id: 18,
    Image: Nike_Sneaker_11,
    productName: "Nike Sneakers 11",
    itemContainer: "5 items left",
    oldPrice: "$290,000",
    newPrice: "$250,000",
    category: "male Shoes",
      discount: "-29%"
  },
  {
    id: 19,
    Image: PumTrainSneakers,
    productName: "Puma train Sneakers",
    itemContainer: "5 items left",
    oldPrice: "$200,000",
    newPrice: "$350,000",
    category: "male Shoes",
      discount: "-22%"
  },
  {
    id: 20,
    Image: PumTrainSneakers_2,
    productName: "Puma train Sneakers 11",
    itemContainer: "10 items left",
    oldPrice: "$200,000",
    newPrice: "$750,000",
    category: "male Shoes",
      discount: "-27%"
  },
  {
    id: 21,
    Image: KswissHeel,
    productName: "K-swiss Heel",
    itemContainer: "10 items left",
    oldPrice: "$40,000",
    newPrice: "$80,000",
    category: "female Shoes",
      discount: "-34%"
  },
  {
    id: 22,
    Image: KswissHeel,
    productName: "K-swiss Heel",
    itemContainer: "10 items left",
    oldPrice: "$40,000",
    newPrice: "$90,000",
    category: "female Shoes",
  },
  {
    id: 23,
    Image: KswissHeel,
    productName: "K-swiss Heel",
    itemContainer: "10 items left",
    oldPrice: "$40,000",
    newPrice: "$60,000",
    category: "female Shoes",
  },
  {
    id: 24,
    Image: KswissHeel,
    productName: "K-swiss Heel",
    itemContainer: "10 items left",
    oldPrice: "$40,000",
    newPrice: "$100,000",
    category: "female Shoes",
  },
  {
    id: 25,
    Image: KswissHeel,
    productName: "K-swiss Heel",
    itemContainer: "10 items left",
    oldPrice: "$40,000",
    newPrice: "$670,000",
    category: "female Shoes",
  },
  {
    id: 26,
    Image: Nike_Sneaker_11,
    productName: "Nike Sneakers 11",
    itemContainer: "5 items left",
    oldPrice: "$290,000",
    newPrice: "$230,000",
    category: "male Shoes",
  },
  {
    id: 27,
    Image: PumTrainSneakers,
    productName: "Puma train Sneakers",
    itemContainer: "5 items left",
    oldPrice: "$200,000",
    newPrice: "$850,000",
    category: "male Shoes",
  },
  {
    id: 28,
    Image: PumTrainSneakers,
    productName: "Puma train Sneakers",
    itemContainer: "5 items left",
    oldPrice: "$200,000",
    newPrice: "$450,000",
    category: "male Shoes",
  },
  {
    id: 29,
    Image: PumTrainSneakers,
    productName: "Puma train Sneakers",
    itemContainer: "5 items left",
    oldPrice: "$200,000",
    newPrice: "$650,000",
    category: "male Shoes",
     Brand: "Puma"
  },
  {
    id: 30,
    Image: Nike_Sneaker_11,
    productName: "Nike Sneakers 11",
    itemContainer: "5 items left",
    oldPrice: "$290,000",
    newPrice: "$250,000",
    category: "male Shoes",
     Brand: "Nike"
  },
  {
    id: 31,
    Image: PumTrainSneakers,
    productName: "Puma train Sneakers",
    itemContainer: "5 items left",
    oldPrice: "$200,000",
    newPrice: "$350,000",
    category: "male Shoes",
     Brand: "Puma"
  },
  {
    id: 32,
    Image: PumTrainSneakers_2,
    productName: "Puma train Sneakers 11",
    itemContainer: "10 items left",
    oldPrice: "$200,000",
    newPrice: "$750,000",
    category: "male Shoes",
  },
  {
    id: 33,
    Image: KswissHeel,
    productName: "K-swiss Heel",
    itemContainer: "10 items left",
    oldPrice: "$40,000",
    newPrice: "$80,000",
    category: "male Shoes",
  },
  {
    id: 34,
    Image: KswissHeel,
    productName: "K-swiss Heel",
    itemContainer: "10 items left",
    oldPrice: "$40,000",
    newPrice: "$90,000",
    category: "male Shoes",
  },
  {
    id: 36,
    Image: KswissHeel,
    productName: "K-swiss Heel",
    itemContainer: "10 items left",
    oldPrice: "$40,000",
    newPrice: "$60,000",
    category: "female Shoes",
  },
  {
    id: 37,
    Image: KswissHeel,
    productName: "K-swiss Heel",
    itemContainer: "10 items left",
    oldPrice: "$40,000",
    newPrice: "$100,000",
    category: "female Shoes",
  },
  {
    id: 38,
    Image: KswissHeel,
    productName: "K-swiss Heel",
    itemContainer: "10 items left",
    oldPrice: "$40,000",
    newPrice: "$670,000",
    category: "male Shoes",
  },
  {
    id: 39,
    Image: Nike_Sneaker_11,
    productName: "Nike Sneakers 11",
    itemContainer: "5 items left",
    oldPrice: "$290,000",
    newPrice: "$230,000",
    category: "male Shoes",
    Brand: "Nike"
  },
  {
    id: 40,
    Image: PumTrainSneakers,
    productName: "Puma train Sneakers",
    itemContainer: "5 items left",
    oldPrice: "$200,000",
    newPrice: "$850,000",
    category: "male Shoes",
    Brand: "Puma"
  },
  {
    id: 41,
    Image: PumTrainSneakers,
    productName: "Puma train Sneakers",
    itemContainer: "5 items left",
    oldPrice: "$200,000",
    newPrice: "$450,000",
    category: "male Shoes",
    Brand: "Puma",
  },
  {
    id: 42,
    Image: PumTrainSneakers,
    productName: "Puma train Sneakers",
    itemContainer: "5 items left",
    oldPrice: "$200,000",
    newPrice: "$650,000",
    category: "male Shoes",
    Brand: "Puma",
  },
  {
    id: 43,
    Image: Nike_Sneaker_11,
    productName: "Nike Sneakers 11",
    itemContainer: "5 items left",
    oldPrice: "$290,000",
    newPrice: "$250,000",
    category: "male Shoes",
    Brand: "Nike",
  },
  {
    id: 44,
    Image: PumTrainSneakers,
    productName: "Puma train Sneakers",
    itemContainer: "5 items left",
    oldPrice: "$200,000",
    newPrice: "$350,000",
    category: "male Shoes",
  },
  {
    id: 45,
    Image: PumTrainSneakers_2,
    productName: "Puma train Sneakers 11",
    itemContainer: "10 items left",
    oldPrice: "$200,000",
    newPrice: "$750,000",
    category: "male Shoes",
  },
  {
    id: 46,
    Image: KswissHeel,
    productName: "K-swiss Heel",
    itemContainer: "10 items left",
    oldPrice: "$40,000",
    newPrice: "$80,000",
    category: "Male Shoes",
  },
  {
    id: 47,
    Image: KswissHeel,
    productName: "K-swiss Heel",
    itemContainer: "10 items left",
    oldPrice: "$40,000",
    newPrice: "$90,000",
    category: "Male Shoes",
  },
  {
    id: 48,
    Image: KswissHeel,
    productName: "K-swiss Heel",
    itemContainer: "10 items left",
    oldPrice: "$40,000",
    newPrice: "$60,000",
    category: "male Shoes",
  },
  {
    id: 49,
    Image: KswissHeel,
    productName: "K-swiss Heel",
    itemContainer: "10 items left",
    oldPrice: "$40,000",
    newPrice: "$100,000",
    category: "female Shoes",
  },
  {
    id: 50,
    Image: KswissHeel,
    productName: "K-swiss Heel",
    itemContainer: "10 items left",
    oldPrice: "$40,000",
    newPrice: "$670,000",
    category: "female Shoes",
  },
  {
    id: 51,
    Image: Nike_Sneaker_11,
    productName: "Nike Sneakers 11",
    itemContainer: "5 items left",
    oldPrice: "$290,000",
    newPrice: "$230,000",
    category: "female Shoes",
  },
  {
    id: 52,
    Image: PumTrainSneakers,
    productName: "Puma train Sneakers",
    itemContainer: "5 items left",
    oldPrice: "$200,000",
    newPrice: "$850,000",
    category: "female Shoes",
  },
  {
    id: 53,
    Image: PumTrainSneakers,
    productName: "Puma train Sneakers",
    itemContainer: "5 items left",
    oldPrice: "$200,000",
    newPrice: "$450,000",
    category: "female Shoes",
  },
  {
    id: 54,
    Image: PumTrainSneakers,
    productName: "Puma train Sneakers",
    itemContainer: "5 items left",
    oldPrice: "$200,000",
    newPrice: "$650,000",
    category: "female Shoes",
  },
  {
    id: 56,
    Image: Nike_Sneaker_11,
    productName: "Nike Sneakers 11",
    itemContainer: "5 items left",
    oldPrice: "$290,000",
    newPrice: "$250,000",
    category: "female Shoes",
  },
  {
    id: 43,
    Image: PumTrainSneakers,
    productName: "Puma train Sneakers",
    itemContainer: "5 items left",
    oldPrice: "$200,000",
    newPrice: "$350,000",
  },
  {
    id: 44,
    Image: PumTrainSneakers_2,
    productName: "Puma train Sneakers 11",
    itemContainer: "10 items left",
    oldPrice: "$200,000",
    newPrice: "$750,000",
  },
  {
    id: 45,
    Image: KswissHeel,
    productName: "K-swiss Heel",
    itemContainer: "10 items left",
    oldPrice: "$40,000",
    newPrice: "$80,000",
  },
  {
    id: 46,
    Image: KswissHeel,
    productName: "K-swiss Heel",
    itemContainer: "10 items left",
    oldPrice: "$40,000",
    newPrice: "$90,000",
  },
  {
    id: 47,
    Image: KswissHeel,
    productName: "K-swiss Heel",
    itemContainer: "10 items left",
    oldPrice: "$40,000",
    newPrice: "$60,000",
  },
  {
    id: 48,
    Image: KswissHeel,
    productName: "K-swiss Heel",
    itemContainer: "10 items left",
    oldPrice: "$40,000",
    newPrice: "$100,000",
  },
  {
    id: 49,
    Image: KswissHeel,
    productName: "K-swiss Heel",
    itemContainer: "10 items left",
    oldPrice: "$40,000",
    newPrice: "$670,000",
  },
  {
    id: 50,
    Image: Nike_Sneaker_11,
    productName: "Nike Sneakers 11",
    itemContainer: "5 items left",
    oldPrice: "$290,000",
    newPrice: "$230,000",
  },
  {
    id: 51,
    Image: PumTrainSneakers,
    productName: "Puma train Sneakers",
    itemContainer: "5 items left",
    oldPrice: "$200,000",
    newPrice: "$850,000",
  },
  {
    id: 52,
    Image: PumTrainSneakers,
    productName: "Puma train Sneakers",
    itemContainer: "5 items left",
    oldPrice: "$200,000",
    newPrice: "$450,000",
  },
  {
    id: 53,
    Image: PumTrainSneakers,
    productName: "Puma train Sneakers",
    itemContainer: "5 items left",
    oldPrice: "$200,000",
    newPrice: "$650,000",
  },
  {
    id: 54,
    Image: Nike_Sneaker_11,
    productName: "Nike Sneakers 11",
    itemContainer: "5 items left",
    oldPrice: "$290,000",
    newPrice: "$250,000",
  },
  {
    id: 55,
    Image: PumTrainSneakers,
    productName: "Puma train Sneakers",
    itemContainer: "5 items left",
    oldPrice: "$200,000",
    newPrice: "$350,000",
  },
  {
    id: 56,
    Image: PumTrainSneakers_2,
    productName: "Puma train Sneakers 11",
    itemContainer: "10 items left",
    oldPrice: "$200,000",
    newPrice: "$750,000",
  },
  {
    id: 57,
    Image: KswissHeel,
    productName: "K-swiss Heel",
    itemContainer: "10 items left",
    oldPrice: "$40,000",
    newPrice: "$80,000",
  },
  {
    id: 58,
    Image: KswissHeel,
    productName: "K-swiss Heel",
    itemContainer: "10 items left",
    oldPrice: "$40,000",
    newPrice: "$90,000",
  },
  {
    id: 59,
    Image: KswissHeel,
    productName: "K-swiss Heel",
    itemContainer: "10 items left",
    oldPrice: "$40,000",
    newPrice: "$60,000",
  },
  {
    id: 60,
    Image: KswissHeel,
    productName: "K-swiss Heel",
    itemContainer: "10 items left",
    oldPrice: "$40,000",
    newPrice: "$100,000",
  },
  {
    id: 61,
    Image: KswissHeel,
    productName: "K-swiss Heel",
    itemContainer: "10 items left",
    oldPrice: "$40,000",
    newPrice: "$670,000",
  },
  {
    id: 62,
    Image: Nike_Sneaker_11,
    productName: "Nike Sneakers 11",
    itemContainer: "5 items left",
    oldPrice: "$290,000",
    newPrice: "$230,000",
  },
  {
    id: 63,
    Image: PumTrainSneakers,
    productName: "Puma train Sneakers",
    itemContainer: "5 items left",
    oldPrice: "$200,000",
    newPrice: "$850,000",
  },
  {
    id: 64,
    Image: PumTrainSneakers,
    productName: "Puma train Sneakers",
    itemContainer: "5 items left",
    oldPrice: "$200,000",
    newPrice: "$450,000",
  },
  {
    id: 65,
    Image: PumTrainSneakers,
    productName: "Puma train Sneakers",
    itemContainer: "5 items left",
    oldPrice: "$200,000",
    newPrice: "$650,000",
  },
  {
    id: 66,
    Image: Nike_Sneaker_11,
    productName: "Nike Sneakers 11",
    itemContainer: "5 items left",
    oldPrice: "$290,000",
    newPrice: "$250,000",
  },
  {
    id: 67,
    Image: PumTrainSneakers,
    productName: "Puma train Sneakers",
    itemContainer: "5 items left",
    oldPrice: "$200,000",
    newPrice: "$350,000",
  },
  {
    id: 68,
    Image: PumTrainSneakers_2,
    productName: "Puma train Sneakers 11",
    itemContainer: "10 items left",
    oldPrice: "$200,000",
    newPrice: "$750,000",
  },
  {
    id: 69,
    Image: KswissHeel,
    productName: "K-swiss Heel",
    itemContainer: "10 items left",
    oldPrice: "$40,000",
    newPrice: "$80,000",
  },
  {
    id: 70,
    Image: KswissHeel,
    productName: "K-swiss Heel",
    itemContainer: "10 items left",
    oldPrice: "$40,000",
    newPrice: "$90,000",
  },
  {
    id: 71,
    Image: KswissHeel,
    productName: "K-swiss Heel",
    itemContainer: "10 items left",
    oldPrice: "$40,000",
    newPrice: "$60,000",
  },
  {
    id: 72,
    Image: KswissHeel,
    productName: "K-swiss Heel",
    itemContainer: "10 items left",
    oldPrice: "$40,000",
    newPrice: "$100,000",
  },
  {
    id: 73,
    Image: KswissHeel,
    productName: "K-swiss Heel",
    itemContainer: "10 items left",
    oldPrice: "$40,000",
    newPrice: "$670,000",
  },
  {
    id: 74,
    Image: Nike_Sneaker_11,
    productName: "Nike Sneakers 11",
    itemContainer: "5 items left",
    oldPrice: "$290,000",
    newPrice: "$230,000",
  },
  {
    id: 75,
    Image: PumTrainSneakers,
    productName: "Puma train Sneakers",
    itemContainer: "5 items left",
    oldPrice: "$200,000",
    newPrice: "$850,000",
  },
  {
    id: 76,
    Image: PumTrainSneakers,
    productName: "Puma train Sneakers",
    itemContainer: "5 items left",
    oldPrice: "$200,000",
    newPrice: "$450,000",
  },
  {
    id: 77,
    Image: PumTrainSneakers,
    productName: "Puma train Sneakers",
    itemContainer: "5 items left",
    oldPrice: "$200,000",
    newPrice: "$650,000",
  },
  {
    id: 78,
    Image: Nike_Sneaker_11,
    productName: "Nike Sneakers 11",
    itemContainer: "5 items left",
    oldPrice: "$290,000",
    newPrice: "$250,000",
  },
  {
    id: 79,
    Image: PumTrainSneakers,
    productName: "Puma train Sneakers",
    itemContainer: "5 items left",
    oldPrice: "$200,000",
    newPrice: "$350,000",
  },
  {
    id: 80,
    Image: PumTrainSneakers_2,
    productName: "Puma train Sneakers 11",
    itemContainer: "10 items left",
    oldPrice: "$200,000",
    newPrice: "$750,000",
  },
  {
    id: 81,
    Image: KswissHeel,
    productName: "K-swiss Heel",
    itemContainer: "10 items left",
    oldPrice: "$40,000",
    newPrice: "$80,000",
  },
  {
    id: 82,
    Image: KswissHeel,
    productName: "K-swiss Heel",
    itemContainer: "10 items left",
    oldPrice: "$40,000",
    newPrice: "$90,000",
  },
  {
    id: 83,
    Image: KswissHeel,
    productName: "K-swiss Heel",
    itemContainer: "10 items left",
    oldPrice: "$40,000",
    newPrice: "$60,000",
  },
  {
    id: 84,
    Image: KswissHeel,
    productName: "K-swiss Heel",
    itemContainer: "10 items left",
    oldPrice: "$40,000",
    newPrice: "$100,000",
  },
  {
    id: 85,
    Image: KswissHeel,
    productName: "K-swiss Heel",
    itemContainer: "10 items left",
    oldPrice: "$40,000",
    newPrice: "$670,000",
  },
  {
    id: 86,
    Image: Nike_Sneaker_11,
    productName: "Nike Sneakers 11",
    itemContainer: "5 items left",
    oldPrice: "$290,000",
    newPrice: "$230,000",
  },
  {
    id: 87,
    Image: PumTrainSneakers,
    productName: "Puma train Sneakers",
    itemContainer: "5 items left",
    oldPrice: "$200,000",
    newPrice: "$850,000",
  },
  {
    id: 89,
    Image: PumTrainSneakers,
    productName: "Puma train Sneakers",
    itemContainer: "5 items left",
    oldPrice: "$200,000",
    newPrice: "$450,000",
  },
  {
    id: 90,
    Image: PumTrainSneakers,
    productName: "Puma train Sneakers",
    itemContainer: "5 items left",
    oldPrice: "$200,000",
    newPrice: "$650,000",
  },
  {
    id: 91,
    Image: Nike_Sneaker_11,
    productName: "Nike Sneakers 11",
    itemContainer: "5 items left",
    oldPrice: "$290,000",
    newPrice: "$250,000",
  },
  {
    id: 92,
    Image: PumTrainSneakers,
    productName: "Puma train Sneakers",
    itemContainer: "5 items left",
    oldPrice: "$200,000",
    newPrice: "$350,000",
  },
  {
    id: 93,
    Image: PumTrainSneakers_2,
    productName: "Puma train Sneakers 11",
    itemContainer: "10 items left",
    oldPrice: "$200,000",
    newPrice: "$750,000",
  },
  {
    id: 94,
    Image: KswissHeel,
    productName: "K-swiss Heel",
    itemContainer: "10 items left",
    oldPrice: "$40,000",
    newPrice: "$80,000",
  },
  {
    id: 95,
    Image: KswissHeel,
    productName: "K-swiss Heel",
    itemContainer: "10 items left",
    oldPrice: "$40,000",
    newPrice: "$90,000",
  },
  {
    id: 96,
    Image: KswissHeel,
    productName: "K-swiss Heel",
    itemContainer: "10 items left",
    oldPrice: "$40,000",
    newPrice: "$60,000",
  },
  {
    id: 97,
    Image: KswissHeel,
    productName: "K-swiss Heel",
    itemContainer: "10 items left",
    oldPrice: "$40,000",
    newPrice: "$100,000",
  },
  {
    id: 98,
    Image: KswissHeel,
    productName: "K-swiss Heel",
    itemContainer: "8 items left",
    oldPrice: "$40,000",
    newPrice: "$670,000",
  },
  {
    id: 99,
    Image: Nike_Sneaker_11,
    productName: "Nike Sneakers 11",
    itemContainer: "5 items left",
    oldPrice: "$290,000",
    newPrice: "$230,000",
  },
  {
    id: 100,
    Image: PumTrainSneakers,
    productName: "Puma train Sneakers",
    itemContainer: "5 items left",
    oldPrice: "$200,000",
    newPrice: "$850,000",
  },
  {
    id: 101,
    Image: PumTrainSneakers,
    productName: "Puma train Sneakers",
    itemContainer: "5 items left",
    oldPrice: "$200,000",
    newPrice: "$450,000",
  },
  {
    id: 102,
    Image: PumTrainSneakers,
    productName: "Puma train Sneakers",
    itemContainer: "5 items left",
    oldPrice: "$200,000",
    newPrice: "$650,000",
  },
  {
    id: 103,
    Image: Nike_Sneaker_11,
    productName: "Nike Sneakers 11",
    itemContainer: "5 items left",
    oldPrice: "$290,000",
    newPrice: "$250,000",
  },
  {
    id: 104,
    Image: PumTrainSneakers,
    productName: "Puma train Sneakers",
    itemContainer: "5 items left",
    oldPrice: "$200,000",
    newPrice: "$350,000",
  },
  {
    id: 105,
    Image: PumTrainSneakers_2,
    productName: "Puma train Sneakers 11",
    itemContainer: "10 items left",
    oldPrice: "$200,000",
    newPrice: "$750,000",
  },
  {
    id: 106,
    Image: KswissHeel,
    productName: "K-swiss Heel",
    itemContainer: "10 items left",
    oldPrice: "$40,000",
    newPrice: "$80,000",
  },
  {
    id: 107,
    Image: KswissHeel,
    productName: "K-swiss Heel",
    itemContainer: "10 items left",
    oldPrice: "$40,000",
    newPrice: "$90,000",
  },
  {
    id: 108,
    Image: KswissHeel,
    productName: "K-swiss Heel",
    itemContainer: "10 items left",
    oldPrice: "$40,000",
    newPrice: "$60,000",
  },
  {
    id: 109,
    Image: KswissHeel,
    productName: "K-swiss Heel",
    itemContainer: "12 items left",
    oldPrice: "$40,000",
    newPrice: "$Good,000",
  },
];

export { priceData4ScrollingPage, priceData4ProductDisplay };
